kind: Service
apiVersion: v1
metadata:
  name: hail-search
  namespace: seqr-prototype
  labels:
    name: hail-search
    deployment: prototype
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    name: hail-search
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name:  hail-search
  namespace: seqr-prototype
  labels:
    app.kubernetes.io/name:  hail-search
    name:  hail-search
    deployment: prototype
spec:
  replicas: 4
  selector:
    matchLabels:
      name: hail-search
  template:
    metadata:
      labels:
        name: hail-search
        app.kubernetes.io/name: hail-search
        deployment: prototype
    spec:
      volumes:
      - name: hail-datasets
        emptyDir:
          sizeLimit: 40Gi
          medium: "Memory"
      containers:
      - name: hail-search-pod
        ports:
        - containerPort: 5000
          protocol: TCP
        imagePullPolicy: Always
        image: gcr.io/seqr-project/seqr:prototype-hail-search
        volumeMounts:
        - name: hail-datasets
          mountPath: /hail_datasets
          readOnly: true
        resources:
          requests:
            memory: "55Gi"
            cpu: "7"
          limits:
            memory: "55Gi"
            cpu: "7"
      initContainers:
        - name: init-data
          image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
#          command: ['gsutil', '-m', 'rsync', '-r', 'gs://hail-backend-datasets/all_data', '/hail_datasets']
          command: ['gsutil', '-m', 'rsync', '-r', 'gs://hail-backend-datasets/test_data', '/hail_datasets']
          volumeMounts:
            - name: hail-datasets
              mountPath: /hail_datasets
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      nodeSelector:
        cloud.google.com/gke-nodepool: 'spark-nodes'
---
