name: Testing helm update
on:
  push:
    branches:
      - test-helm-update

jobs:
  helm_update:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve tgg-helm repo for broad seqr chart
        uses: actions/checkout@v3
        with:
          repository: broadinstitute/tgg-helm
          ref: main
          persist-credentials: false
          fetch-depth: 0

      - name: update image tag in the broad seqr chart
        uses: mikefarah/yq@v4.22.1
        with:
          cmd: >
            yq -i '.seqr.image.tag = "${GITHUB_SHA}"' charts/broad-seqr/values-dev.yaml

      - name: Commit and Push changes
        uses: Andro999b/push@v1.3
        with:
          repository: broadinstitute/tgg-helm
          branch: main
          github_token: ${{ secrets.SEQR_VERSION_UPDATE_TOKEN }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          author_name: tgg-automation
          message: "Update seqr dev release docker tag to ${GITHUB_SHA}"
