name: Update seqr Version
on:
  push:
    branches:
      - seqr-helm-version
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get seqr version
        run: |
          seqr_version=$(grep SEQR_VERSION ./settings.py | sed -n "s/^.*=[ ]*'\(.*\)'/\1/p")
          commit_id=$(git rev-parse --short HEAD)
          echo "SEQR_VERSION=$seqr_version-$commit_id" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          repository: broadinstitute/seqr-helm
      - name: Update appVersion in the seqr HelmChart Chart.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'charts/seqr/Chart.yaml'
          propertyPath: 'appVersion'
          value: ${{ env.SEQR_VERSION }}
          repository: broadinstitute/seqr-helm
          masterBranchName: main
          branch: seqr-version-${{ env.SEQR_VERSION }}
          targetBranch: main
          createPR: true
          message: 'Update appVersion to ${{ env.SEQR_VERSION }}'
          token: ${{ secrets.SEQR_VERSION_UPDATE_TOKEN }}
