name: Update seqr Version
on:
  push:
    branches:
      - seqr-helm-version
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get seqr version
        run: |
          seqr_version=$(grep "SEQR_VERSION[ ]*=[ ]*'.*'" ./settings.py | sed -n "s/^.*'\(.*\)'/\1/p")
          commit_id=$(git rev-parse --short HEAD)
          echo "SEQR_VERSION=$seqr_version-$commit_id" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          repository: broadinstitute/seqr-helm
          ref: main
          ssh-key: ${{ secrets.SEQR_VERSION_UPDATE_TOKEN }}
          persist-credentials: true
      - name: Update appVersion in seqr Chart file
        uses: mikefarah/yq@v4.22.1
        with:
          cmd: >
            yq -i '.appVersion = "${{ env.SEQR_VERSION }}"' charts/seqr/Chart.yaml
      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          git config --local user.name "tgg-automation"
          git commit -m "Update seqr version" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          ssh: true
          repository: broadinstitute/seqr-helm
          branch: main
