name: Update seqr Version
on:
  push:
    branches:
      - seqr-helm-version
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get seqr version
        id: seqr
        run:
          echo "::set-output name=commit_id::$(git rev-parse --short HEAD)"
      - uses: actions/checkout@v3
        with:
          repository: broadinstitute/seqr-helm
      - name: Update appVersion in the seqr HelmChart Chart.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'charts/seqr/Chart.yaml'
          propertyPath: 'appVersion'
          value: ${{ steps.seqr.outputs.commit_id }}
          repository: broadinstitute/seqr-helm
          masterBranchName: main
          branch: seqr-version-${{ steps.seqr.outputs.commit_id }}
          targetBranch: main
          createPR: true
          message: 'Update appVersion to ${{ steps.seqr.outputs.commit_id }}
          token: ${{ secrets.SEQR_VERSION_UPDATE_TOKEN }}
