name: Update seqr Version
on:
  push:
    branches:
      - seqr-helm-version
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get seqr version
        run: |
          seqr_version=$(grep "SEQR_VERSION[ ]*=[ ]*'.*'" ./settings.py | sed -n "s/^.*'\(.*\)'/\1/p")
          commit_id=$(git rev-parse --short HEAD)
          echo "SEQR_VERSION=$seqr_version-$commit_id" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          repository: broadinstitute/seqr-helm
          ref: main
      - name: Update appVersion in seqr Chart file
        uses: mikefarah/yq@v4.22.1
        with:
          cmd: >
            yq -i '.appVersion = "${{ env.SEQR_VERSION }}"' charts/seqr/Chart.yaml
      - name: Create Pull Request
        id: createpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.SEQR_VERSION_UPDATE_TOKEN }}
          commit-message: 'Update appVersion to ${{ env.SEQR_VERSION }}'
          committer: shifa <shifa@broadinstitute.org>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          labels: automation
          title: 'Update appVersion to ${{ env.SEQR_VERSION }}'
          body: Automated changes triggered by a push to the release branch in the seqr [repo](https://github.com/broadinstitute/seqr).
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.createpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.createpr.outputs.pull-request-url }}"
