name: Update seqr Version
on:
  push:
    branches:
      # - seqr-helm-version  # for testing
      - master
      - dev
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get seqr version
        run: |
          seqr_version=$(grep "SEQR_VERSION[ ]*=[ ]*'.*'" ./settings.py | sed -n "s/^.*'\(.*\)'/\1/p")
          commit_id=$(git rev-parse --short HEAD)
          echo "SEQR_VERSION=$seqr_version-$commit_id" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          repository: broadinstitute/seqr-helm
          ref: main
          persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0  # otherwise, you will failed to push refs to dest repo
      - name: Update appVersion in seqr Chart file
        uses: mikefarah/yq@v4.22.1
        with:
          cmd: >
            yq -i '.appVersion = "${{ env.SEQR_VERSION }}"' charts/seqr/Chart.yaml
      - name: Commit and Push changes
        uses: Andro999b/push@v1.3
        with:
          repository: broadinstitute/seqr-helm
          branch: main
          github_token: ${{ secrets.SEQR_VERSION_UPDATE_TOKEN }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          author_name: tgg-automation
          message: 'Update appVersion with seqr version'
