name: seqr dev release
on:
  push:
    branches:
      - seqr-helm-version  # for testing
      # - master
      # - dev

permissions:
  id-token: write

jobs:
  docker:
    # needs: unit-tests ?
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: authenticate to google cloud
        id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/${{ secrets.GOOGLE_PROJECT_ID }}/locations/global/workloadIdentityPools/testing-actions-pool/providers/testing-github-actions'
          service_account: '${{ secrets.RUN_SA_EMAIL }}'

      - name: 'setup gcloud sdk'
        uses: google-github-actions/setup-gcloud@v0

      - name: Build and push images
        run: |-
          gcloud builds submit --quiet --substitutions="COMMIT_SHA=${GITHUB_SHA},_CUSTOM_BRANCH_TAG=test-github-actions" -f seqr-docker.cloudbuild.yaml .

  # run:
  #   runs-on: ubuntu-latest
  #   needs: docker
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: get seqr version
  #       run: |
  #         seqr_version=$(grep "SEQR_VERSION[ ]*=[ ]*'.*'" ./settings.py | sed -n "s/^.*'\(.*\)'/\1/p")
  #         commit_id=$(git rev-parse --short HEAD)
  #         echo "SEQR_VERSION=$seqr_version-$commit_id" >> $GITHUB_ENV
  #     - uses: actions/checkout@v3
  #       with:
  #         repository: broadinstitute/seqr-helm
  #         ref: main
  #         persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
  #         fetch-depth: 0  # otherwise, you will failed to push refs to dest repo
  #     - name: Update appVersion in seqr Chart file
  #       uses: mikefarah/yq@v4.22.1
  #       with:
  #         cmd: >
  #           yq -i '.appVersion = "${{ env.SEQR_VERSION }}"' charts/seqr/Chart.yaml
  #     - name: Commit and Push changes
  #       uses: Andro999b/push@v1.3
  #       with:
  #         repository: broadinstitute/seqr-helm
  #         branch: main
  #         github_token: ${{ secrets.SEQR_VERSION_UPDATE_TOKEN }}
  #         author_email: ${{ github.actor }}@users.noreply.github.com
  #         author_name: tgg-automation
  #         message: 'Update appVersion with seqr version'
